hackerton_4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from main import urls as main_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(main_urls)),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'main'

urlpatterns = [
	path('', views.home, name="home"),
	path('select_game', views.select_game, name="select_game"),
	path('start_game/<str:gamename>/', views.start_game, name="start_game"),
	path('music_list_of_game/<str:gamename>/', views.music_list_of_game, name='music_list_of_game'),
	path('end_game/<int:score>/', views.end_game, name='end_game')
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save


class music(models.Model):
    id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=100)
    artist = models.CharField(max_length=100)
    like = models.IntegerField()
    album_cover = models.ImageField(upload_to="music/%Y/%m/%d")

    def __str__(self):
        return '{} - {}'.format(self.title, self.artist)


class game(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class musicgame(models.Model):
    music = models.ForeignKey('music', on_delete=models.CASCADE, )
    game = models.ForeignKey('game', on_delete=models.CASCADE, )

    def __str__(self):
        return '{} : {}'.format(str(self.game), str(self.music))


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    current_score = models.PositiveIntegerField(default=0)
    max_score = models.PositiveIntegerField(default=0)
    current_game = models.CharField(max_length=100, default='')

    def __str__(self):
        return self.user.username


class success_music(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    music = models.ForeignKey('music', on_delete=models.CASCADE)

    def __str__(self):
        return '{}: {}'.format(str(self.user), str(self.music))


class end_page_picture(models.Model):
    image = models.ImageField(upload_to="fail")
    text = models.CharField(max_length=100)


def on_post_save_for_user(sender, **kwargs):
    if kwargs['created']:
        user = kwargs['instance']
        Profile.objects.create(user=user)


post_save.connect(on_post_save_for_user, sender=settings.AUTH_USER_MODEL)

main/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import random

from rest_framework.decorators import api_view
from rest_framework.response import Response

from main.models import game, musicgame, end_page_picture
from main.serializers import MusicGameSerializer


def home(request):
    return render(request, 'main/home.html')


def select_game(request):
    games = game.objects.all()
    context = {'games': games}
    return render(request, 'main/select_game.html', context)


def start_game(request, gamename):
    context = {'gamename': gamename}
    return render(request, 'main/start_game.html', context)


@api_view(['POST'])
def music_list_of_game(request, gamename):
    if request.method == 'POST':
        gamename = game.objects.filter(name=gamename)
        music_list = musicgame.objects.filter(game=gamename[0]).order_by('?')
        serializer = MusicGameSerializer(music_list, many=True)
        return Response(serializer.data)


def end_game(request, score):
    image_number = random.randint(2, 8)
    picture = end_page_picture.objects.get(pk=image_number)
    context = {
        'picture': picture,
        'score': score,
    }
    return render(request, 'main/end_game.html', context)

main/templates/main/end_game.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}
<style> body, html { height: 100%; margin: 0; } .bg { /* The image used */ background-image: url("{{ picture.image.url }}"); /* Full height */ height: 100%; /* Center and scale the image nicely */ background-position: center; background-repeat: no-repeat; background-size: cover; }

.bg > div { margin: 0; z-index: 100; background-color:white; width: 50%; }

.center { position: relative; left: 25%; top: 60%; text-align: center; opacity: 0.6; font-weight: 900; font-size: 2rem; padding: 1%; }

button { margin-top: 20px; color: #[707070](https://www.notion.so/707070); background-color: #fff; border-color: #[707070](https://www.notion.so/707070); width: 73px; cursor: default; padding: 8px; padding-left: 10px; padding-right: 10px; font-weight: 350; /* font-size: 0.65; */ line-height: 1.15; letter-spacing: .1rem; border-width: 1px; margin-right: 10px; margin-bottom: 10px; box-sizing: border-box; vertical-align: middle; float: none; display: inline-block; }
</style>

<div class='bg'> <div class='center'> {{ picture.text }} <p> 당신의 점수는? {{ score }}점 입니다! </p> <div class="button"> <button class="strat" onclick="location.href='{% url 'main:select_game' %}'">게임시작</button> </div> </div>
</div>

{% endblock %}

main/templates/main/game_fail.html
{% extends 'base.html' %}

{% load staticfiles %}

<!-- css 링크 -->
{% block header %}
<link rel="stylesheet" href="../../../hackerton_4/static/assets/css/game_fail.css">
{% endblock %}

{% block content %}

    <!-- 문제가 틀렸을때 오는 페이지 -->

    <!-- 점수 표시해주는 글 -->
    <div class="fail_content">
        <p class="top">당신의 점수는?</p>
        <h1>점수 넣어 주세요 점</h1>
        <p class="bottom">땡땡땡, 다시해볼까요?</p>

            <!-- 다시하는 버튼 -->
            <div class="button">
                <button class="main">메인으로</button>
                <button class="retry">다시도전</button>
            </div>
    </div>

{% endblock %} 

main/templates/main/home.html
{% extends 'base.html' %}

{% load staticfiles %}

<!-- css 링크 -->
{% block header %}
<style>
    *{
        text-align: center;
    }
    button {
    background-color: white;
    border-color: rgb(30, 255, 0);
    border-radius: 10px;
    width: 100px;
    height: 60px;
    font-size: 20px;
    border-width: 4px;
    margin: auto;
    display: block;
    }
    img{
        margin-top: 10%;
        width: 300px;
    }
</style>
{% endblock %}

{% block content %}

   <!-- 들어왓을떄 바로 보이는 메인 페이지 입니다. -->

   <!-- 배경이미지 -->
   <div class="bg_img">
      <img src="{% static '/images/멜론.jpg' %}" alt="" class="bg">
   </div>

   <!-- 글내용 -->
   <div class="content">
      <h1 class="title">멜론 게임</h1>
      <p>맬론에서는 어떤 키워드가 많이 검색 될까요?</p>
      <p>멜론에서 검색되는 많은 키워드들의 검색량을 비교하는 게임을 시작해 볼까요!</p>
         <div class="button">
            <button class="strat" onclick="location.href='{% url 'main:select_game' %}'">게임시작</button>
         </div>
   </div>

   <!-- 추가될게 있으면 이쪽에 넣으면 될것같아요 -->
   <div class="footer">

   </div>

{% endblock %} 

main/templates/main/select_game.html
{% extends 'base.html' %}
{% load staticfiles %}

<!-- css 링크 -->
{% block header %}
<style>
        *{
            text-align: center;
        }

        button {
        background-color: white;
        border-color: rgb(162, 0, 255);
        border-radius: 10px;
        width: 100px;
        height: 60px;
        font-size: 20px;
        border-width: 4px;
        margin-top: 50px;
        display: inline-block;
        }

        img{
            margin-top: 10%;
            width: 300px;
        }
    </style>
{% endblock %}

{% block content %}

    <!-- 게임 고르는 페이지 입니다. -->

    <!-- 배경이미지 -->
    <div class="bg_img">
        <img src="" alt="" class="bg">
    </div>

    <!-- 글내용 -->
    <div class="content">
        <h1 class="title">멜론 게임</h1>
        <p>비교하고 싶은 키워드를 골라주세요.</p>
            <!-- 카테고리 선택 버튼 -->
            <div class="select_button">
                {% for item in games %}
                <button onclick="location.href='{% url 'main:start_game' item.name %}'">{{item.name}}</button>
                {% endfor %}
            </div>
    </div>

{% endblock %}

main/templates/main/start_game.html
{% extends 'base.html' %}
{% load staticfiles %}

<!-- css 링크 -->
{% block header %}
<!-- <link rel="stylesheet" href="{% static 'assets/css/start_game.css' %}"> -->
<style>
    *{  
        text-align: center;
        margin: 0;
        padding: 0;
    }  
    p{
        color: white;
        font-size: 30px;
    }  
    .left{
        width: 500px;
        height: 500px;
        float: left;
    }
    .right{
        float: right;
    }
    .center{
        position: absolute;
        left: 50%; 
        transform: translateX(-50%);
        z-index: 2;
    }
    img{
        width: 500px;
        height: 500px;
        overflow: hidden;
    }
    .left_content{
        background-color: rgba(0,0,0,0.5);
        width: 50%;
        height: 1080px;
        position: absolute;
        top: 0;
        left: 0;
        color: #fff;
    }
    .right_content{
        position: absolute;
        top: 0;
        right: 0;
        width: 50%;
        height: 1080px;
        background-color: rgba(0,0,0,0.5);
        color: #fff;
    }
    h3{
        margin-top: 45%;
        font-size: 100px;
    }
    h1{
        margin-top: 100px;
        font-size: 70px;
        color: orange;
    }
    button {
    background-color: wheat;
    border-color: orange;
    border-radius: 10px;
    width: 100px;
    height: 60px;
    font-size: 20px;
    border-width: 4px;
    margin: auto;
    display: block;
    }
</style>

{% endblock %}

{% block content %}
<!-- 게임이 시작되면 나오는 페이지 -->

<!-- 왼쪽 -->
<div class="left" data-like="">
    <!-- 투표 왼쪽 이미지 -->
    <img src="" alt="" class="left_img">

    <!-- 왼쪽 정보 -->
    <div class="cover">

    </div>
    <div class="left_content">
        <h3 class="left_title" id="left_title">"왼쪽 정보 이름"</h3>
        <p class="left_Information">
            왼쪽 정보 내용
        </p>
        <p class="left_like">0000검색수</p>
    </div>
</div>

<!-- 가운데 -->
<div class="center">
    <!-- 카테고리 이름 -->
    <h1 class="kategory_name">{{gamename}}</h1>
    <!-- 현재 점수 표시 -->
    <p class="score">현재 점수 : 점수</p>
    <!-- vs 표시 -->
    <!-- <div class="vs">vs</div> -->
</div>

<!-- 오른쪽 -->
<div class="right" data-like="">
    <!-- 오른쪽 이미지 -->
    <img src="" alt="" class="right_img">
    <!-- 오른쪽 내용 -->
    <div class="right_content">
        <h3 class="right_title" data-like="">"오른쪽 정보 이름"</h3>
        <!-- 업,다운 버튼 -->
        <p class="left_Information right_Information">
            오른쪽 정보 내용
        </p>
        <div class="survey_button_">
            <button class="up music" value='0'>더 많이</button>
            <button class="down music" value='0'>더 적게</button>
        </div>
        
    </div>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js" type="text/javascript"></script>
<script src="//code.jquery.com/jquery-1.12.4.min.js"></script>
<script language="javascript">
    $(document).ready(function () {
        var prev_music = ""
        var curr_music = ""
        var correct = ""
        var cnt = 0
        var point = 0
        var csrftoken = $("[name=csrfmiddlewaretoken]").val();
        $.ajax({
            url: '{% url "main:music_list_of_game" gamename %}',
            type: 'POST',
            headers: {
				"X-CSRFToken": csrftoken
			},
            data: {
				'csrfmiddlewaretoken': "{{ csrf_token }}",
			},
            success: function (response) {
                for (var i = 0; i < response.length; i++)
                    console.log(response[i].music)
                prev_music = response[cnt]
                curr_music = response[cnt + 1]
                cnt += 1
                correct = load_quiz(prev_music, curr_music, cnt)
                $(".music").on('click', function () {
                    // alert("클릭한 노래의 좋아요:" + $(this).attr('value'));
                    console.log('---------------------')
                    // correct = load_quiz(prev_music, curr_music, cnt)
                    var answer = $(this).text()
                    console.log(answer)
                    if (correct==answer) {
                        console.log("정답")
                        point += 1
                        $('.score').html('점수: '+point)
                        console.log('점수' + point)
                        cnt += 1
                        prev_music = curr_music
                        curr_music = response[cnt]
                        if (cnt != response.length) {
                            correct = load_quiz(prev_music, curr_music, cnt)
                        } else {
                            console.log('더이상 문제가 없어요')
                            window.location.href = "/end_game/" + point
                        }
                    } else {
                        console.log("오답")
                        console.log('점수' + point)
                        window.location.href = "/end_game/" + point
                    }
                });
            },
            error: function (response) {
                console.log(response);
            }
        });
    });
    function load_quiz(prev_music, curr_music, cnt) {
        console.log('---------------------')
        //좋아요 수 비교해 정답 저장
        if (prev_music.music.like < curr_music.music.like)
            correct = "더 많이"
        else
            correct = "더 적게"
        console.log( window.location.origin+prev_music.music.album_cover)
        $('.left_title').html(prev_music.music.title)
        $('.left_like').html('좋아요: '+prev_music.music.like)
        $('.left_Information').html(prev_music.music.artist)
        $('.left_img').attr('src', prev_music.music.album_cover);
        $('.up').val(prev_music.music.like)
        $('.right_title').html(curr_music.music.title)
        $('.right_Information').html(curr_music.music.artist)
        $('.down').val(curr_music.music.like)
        $('.right_img').attr('src', curr_music.music.album_cover);
        // console.log('정답의 좋아요' + correct.music.like)
        return correct
    }
</script>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html lang="ko">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">

		<!-- 서비스 이름 정해주세요 -->
		<title>멜론 게임</title>
		{% block header %}
		{% endblock %}
	</head>
	<body>	
		{% block content %}


		{% endblock %}

	</body>
</html> 